---
title: "webcrawling"
author: "cwkim"
date: "2019년 4월 18일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())

```


#필요한 패키지를 불러온다
```{r package}
library(tidyverse)
library(httr)
library(rvest)
```


#다음 실시간 검색어가 포함된 웹 페이지의 URL을 복사하여 붙입니다
````{r 다음 주소}
'https://www.daum.net'
````


# HTTP 요청을 실행합니다.
```{r}
res <- GET(url = 'https://www.daum.net')

```



# res 객체를 출력합니다. 

```{r}
print(x = res)
```


# HTTP 응답 상태코드를 확인합니다. 
```{r}
status_code(x = res)
```

# res 객체에 포함된 HTML을 텍스트(계층구조)로 출력합니다.
```{r}
cat(content(x = res, as = 'text', encoding = 'UTF-8'))
```


# HTTP 응답 객체에서 HTML을 읽습니다.
```{r}
html <- read_html(x = res)
```


# HTML에서 CSS로 필요한 요소만 선택합니다.
```{r}
span <- html_nodes(x = html, css ='div.realtime_part > ol > li > div > div:nth-child(1) > span.txt_issue > a')

```

# 실시간 검색어만 추출합니다.

```{r}
searchWords <- html_text(x = span)
```

# 최종 결과를 출력하여 확인합니다. 
```{r}
print(x = searchWords)

```








#코스피

```{r warning=FALSE}

res1 <- GET(url = 'https://finance.naver.com/sise/sise_index.nhn?code=KOSPI', locale='C')
print(x=res1)



res1 %>% read_html(encoding="EUC-KR") %>% html_node(css='#contentarea_left > div.box_top_sub > div > div.subtop_sise_detail > table') %>% html_table(trim=TRUE)

Sys.setlocale(category = 'LC_ALL', locale = 'C')


tbl <- res1 %>% 
  read_html(encoding="EUC-KR") %>% 
  html_node(css = 'table.table_kos_index') %>% 
  html_table(fill = TRUE)


Sys.setlocale(category = 'LC_ALL', locale = 'korean')

glimpse(x = tbl)


#불필요한 string을 제거하고 tbl에 재할당해줍니다
tbl$X2<-tbl$X2 %>% str_remove_all(pattern = '\n|\t')
tbl$X3<-tbl$X3 %>% str_remove_all(pattern = '\n|\t')
tbl$X4<-tbl$X4 %>% str_remove_all(pattern = '\n|\t')

#다시 tbl을 확인합니다
tbl

# X2~X4 칼럼에 상한종목수4 상승종목수 422 보합종목수64 하락종목수408 하한종목수0 이 반복됩니다.
# 이를 제거하고 새로운 표로 만들어줍니다.
tbl$X2[4]
view(tbl)



#new table
attach(tbl)
c1<- c(X1[1:3],X3[1:3],X1[4])
c2=c(X2[1:3],X4[1:3], X2[4])
newtbl=cbind(c1,c2)

#불필요한 빈칸을 제거해줍니다
newtbl[7,2]<-newtbl[7,2] %>% str_remove_all(pattern="                        ")

print(newtbl)
view(newtbl)

```





